name: Build and Deploy Auto
on:
  push:
    branches:
    - main
 
 
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'
        
    - name: Install Angular CLI
      run: npm install -g @angular/cli 

    - name: Install dependencies
      run: npm install

    - name: Build
      run: ng build
      
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
    - id: 'deploy'
      name: Deploy to Cloud Engine
      uses: google-github-actions/deploy-appengine@v1
